services:
  postgres:
    image: postgres:16
    container_name: dolphy-postgres
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Joel
      POSTGRES_DB: dolphy-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
